#cloud-config
users:
  - name: ${user_name}
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
package_update: true
package_upgrade: true
packages:
  - htop
  - fail2ban
  - ufw
  - ca-certificates
  - curl
  - gnupg
  - unzip
  - lsb-release
runcmd:
  - |
    udevadm trigger -c add -s block -p ID_VENDOR=HC --verbose -p ID_MODEL=Volume # https://github.com/hetznercloud/terraform-provider-hcloud/issues/473
  - |
    printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - |
    systemctl enable fail2ban
  - |
    systemctl start fail2ban
  - |
    ufw allow 'OpenSSH'
  - |
    ufw enable
  - |
    sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding yes/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - |
    sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - |
    sed -i '$a AllowUsers ${user_name}' /etc/ssh/sshd_config
  - |
    systemctl restart ssh
  - |
    mkdir -p /etc/apt/keyrings
  - |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
  - |
    apt-get update
  - |
    apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
  - |
    usermod -aG docker ${user_name}
  - |
    systemctl stop docker
  - |
    ln -s /mnt/HC_Volume_* /mnt/docker-volume
  - |
    mkdir -p /etc/docker
  - |
    printf '{ \n  "data-root": "/mnt/docker-volume" \n}' | tee /etc/docker/daemon.json
  - |
    systemctl start docker